version: '{build}'

image: Visual Studio 2017
install:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
  - ps: .\build.ps1 -Target "DefaultCI"

# Tests
test: off